font:
  normal:
    family: FuraCode Nerd Font
    style: Medium
  bold:
    family: FuraCode Nerd Font
    style: Bold
  italic:
    family: FuraCode Nerd Font
    style: Italic
  size: 13
  history: 10000
  offset:
    x: 0
    'y': 0
  glyph_offset:
    x: 0
    'y': 0
  scale_with_dpi: true
  
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x282b3b'
    cursor: '0xbfa5b2'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'

env:
  WINIT_X11_SCALE_FACTOR: '1.0'

window:
  padding:
    x: 4
    y: 4
  dynamic_padding: true
