font:
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  size: 12.5
  history: 10000
  offset:
    x: 0
    'y': 0
  glyph_offset:
    x: 0
    'y': 0
  scale_with_dpi: true
colors:
  primary:
    background: '#2B263A'
    foreground: '#EBF6F2'
  cursor:
    text: '0x282b3b'
    cursor: '0xbfa5b2'
  normal:
    black: '#403E41'
    red: '#FF6188'
    green: '#A9DC76'
    yellow: '#FFD866'
    blue: '#FC9867'
    magenta: '#AB9DF2'
    cyan: '#78DCE8'
    white: '#FCFCFA'
  bright:
    black: '#727072'
    red: '#FF6188'
    green: '#A9DC76'
    yellow: '#FFD866'
    blue: '#FC9867'
    magenta: '#AB9DF2'
    cyan: '#78DCE8'
    white: '#FCFCFA'
